Feature/core batch search endpoint
ropensci/rcoreoa pull request #3
Opened 2017-04-19 14:50 UTC by aresxs91

Extending the core_search function's capabilities to include multiple search queries in case results need to be retrieved from a wide range of requests in a more efficient manner.

## Description

Adding in a POST request to the core_search function and a convenience function to the zzz.R file that will convert a simple character vector, e.g. c("data mining", "machine learning", "semantic web"), to a suitable JSON object required from the endpoint to perform a batch search request. This includes updating of the documentation with the added parameter to the function (called "method" for consistency with the similar core_articles function's parameter) and checks to disallow multiple queries in GET requests for the core_search function.

Moreover, single valued parameters in the JSON objects sent to the endpoints will be unboxed as this is a requirement for all of CORE's endpoints.

## Example

As included in the documentation:

query <- c("data mining", "machine learning", "semantic web")

# post request
res <- core_search(query, method = "POST")
head(res$data)
res$data$id

The "page" and "pageSize" variables will be constant in all individual query requests (may not be the desirable functionality for some but done so for the sake of simplicity).

2017-04-19 19:10 UTC, sckott commented
thanks @aresxs91 

First, a question. Would it be easier to instead of having a new parameter `method` to use `POST` when `length(query) > 1` and `GET` otherwise ?

2017-04-19 19:16 UTC, aresxs91 commented
Hello Scott,

Thanks for your comment. I see, yes that would indeed make it more concise.
I copied your style for the core_articles function there to be honest. I'll
revise it and let you know :)

Best,
Aris

On Wed, 19 Apr 2017 at 20:10 Scott Chamberlain <notifications@github.com>
wrote:

> thanks @aresxs91 <https://github.com/aresxs91>
>
> First, a question. Would it be easier to instead of having a new parameter
> method to use POST when length(query) > 1 and GET otherwise ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ropenscilabs/cored/pull/3#issuecomment-295396302>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AKcM14JrLqVDzYl0e43SgqJf5ogJNvWzks5rxlwzgaJpZM4NBy9S>
> .
>

2017-04-20 19:11 UTC, sckott commented
@aresxs91 ping me when you're done

2017-04-20 19:42 UTC, aresxs91 commented
It seems alright from my end, I haven't made extensive tests for the function but it looks ready.

2017-04-21 17:32 UTC, sckott requested changes
just a few changes

2017-04-21 17:32 UTC, sckott commented on R/core_search.R
> +  switch(
since there's only two options, an if/else makes more sense here i think

2017-04-21 17:32 UTC, sckott commented on R/zzz.R
> +    body = jsonlite::toJSON(body, auto_unbox=T), encode = "json", ...
please use `TRUE` and `FALSE` instead of `T` and `F`

2017-04-21 17:32 UTC, sckott commented on R/zzz.R
> +    as.list(setNames(x, rep("query", length(x))))
namespace `setNames` here like `stats::setNames` since we don't import the stats pkg

2017-04-24 08:59 UTC, aresxs91 commented on R/core_search.R
> +  switch(
Agreed.

2017-04-25 06:02 UTC, sckott commented
thanks very much!

2017-04-25 06:02 UTC, sckott approved these changes

2017-04-25 06:03 UTC, merged