Feature/advanced search query formulation support
ropensci/rcoreoa pull request #6
Opened 2017-04-27 18:28 UTC by aresxs91

A first version of the advanced search endpoint, separate to the core_search endpoint.

### Description

We separated the two endpoints (advanced and simple search) here for consistency/maintainability and also because it was more convenient to work with data.frame types for advanced search queries instead of character strings. The parsing of advanced queries checks each "acceptable" filter included in the query and performs conversions to match Elasticsearch query syntax for either including, excluding string terms, performing field specific searches, etc.

### Related Issue

Fix for #4.

### Example

The following will accept a batch request that will perform a search for "data mining" and "machine learning", excluding the terms "social", "science" and "medicine" respectively. Year ranges are also specified as 2013 to 2014 and 2000 to 2016 respectively.

```
query <- data.frame("all_of_the_words" = c("data mining", "machine learning"),
"without_the_words" = c("social science", "medicine"),"year_from" = c("2013","2000"),  
"year_to" = c("2014", "2016"))
```

res <- core_advanced_search(query)
head(res$data)
res$data[[1]]$id

2017-04-28 21:54 UTC, sckott commented
thanks!

the link https://core.ac.uk/docs/#!/all/advanced_search doesn't seem to link to anything for me, where should that link to?

2017-04-28 22:03 UTC, sckott commented
- tidy line widths to 80 chars or less 
- include a check that the input is a data.frame, since `apply()` i don't think fails well if e.g. a list is given

2017-05-02 10:03 UTC, aresxs91 commented
The link (https://core.ac.uk/docs/#!/all/advanced_search) is actually not public so I've included a description of the information needed in the data frame for advanced search queries in the details section.

Caught red-handed on the line widths!
Agreed with the is.data.frame check.

2017-05-02 16:50 UTC, sckott commented
thanks @aresxs91 -- all done with changes?

2017-05-02 16:52 UTC, aresxs91 commented
Yes, all done, let me know if you spot anything I have missed. Thanks, @sckott

2017-05-02 18:55 UTC, sckott requested changes
looking good, a few more things to change. 

also, can you add some tests in a new test file for the adv. function.

2017-05-02 18:55 UTC, sckott commented on R/core_advanced_search.R
> +    print("query must be a data.frame (see details)")
I wouldn't use `print()` here. Use `stop()` instead, can can just move that up above the block of code like 

```r
stop("query must be a data.frame (see details)")

parsed_advanced_query <- apply(X = query, MARGIN = 1, FUN = 
                                 parse_advanced_search_query)

if(length(parsed_advanced_query) > 1){
  queries <- create_batch_query_list(parsed_advanced_query, page, limit)
  args <- NULL
  
  core_POST(path = "search", key, args, queries, ...)
} else {
  core_GET(path = file.path("search", parsed_advanced_query), key,
           list(page = page, pageSize = limit), ...)
}
```

2017-05-02 18:55 UTC, sckott commented on R/core_advanced_search.R
> +#' 1. `all_of_the_words`: string, with space separated terms that should all exist
there's still 5 lines that have widths > 80 chars. including this one

2017-05-02 18:55 UTC, sckott commented on R/core_advanced_search.R
> +#' character string
add a `@return` tag and describe what is returned

2017-05-02 18:55 UTC, sckott commented on R/zzz.R
> +# Advanced search related functions
- move all these helper functions into a new file with file name indicating what they are, please use `.R` and not `.r`
- be consistent with fxn names, ideally `snake_case`, right now there's combo of camelCase, snake_case and dot.case

2017-05-02 18:55 UTC, sckott commented on R/core_advanced_search.R
> +#' res$data[[1]]$id
you need a closing bracket `}` on a new line after this last examples line

2017-05-02 18:55 UTC, sckott commented on R/zzz.R
> +        ret <- paste(na.omit(x), collapse = sep)
namespace all calls to non-base R pkgs like `stats`, `tools`, etc. 

here, namespace like `stats::na.omit` instead of `na.omit`

2017-05-03 09:33 UTC, aresxs91 commented on R/core_advanced_search.R
> +    print("query must be a data.frame (see details)")
True, missed that while debugging.

2017-05-03 09:38 UTC, aresxs91 commented on R/core_advanced_search.R
> +#' character string
I haven't seen any other of the functions have a @return tag so I will add it in for them too.

Just to mention that the advanced search return the same data type as the rest, a data frame with:
1) "status" as character, 
2) "totalHits" as integer and
3) "data" as list.

2017-05-03 09:47 UTC, aresxs91 commented on R/zzz.R
> +# Advanced search related functions
Agreed, I will move all advanced search related functions.
Will rename fxn_names accordingly

2017-05-03 13:57 UTC, aresxs91 commented
Thanks for you comments again @sckott, as for the advanced search query tests, I guess an approach would be to add a few queries using a random combination of available filters. Would that be enough?

2017-05-03 14:03 UTC, aresxs91 commented on R/core_advanced_search.R
> +#' character string
Adding to my previous comment, I missed that the references tag would actually cover for what the other endpoints return, whereas the advanced search does not have one. I see why you wanted a return tag here, will add it only for this endpoint.

2017-05-03 17:52 UTC, sckott commented on R/core_advanced_search.R
> +#' character string
Thanks for adding `@return` (sometimes I forget them too)

that sounds good what you described for return

2017-05-03 17:52 UTC, sckott approved these changes

2017-05-03 17:53 UTC, sckott commented
Thanks for adding some tests, we can adjust those as we see fit later. 

Did you do all changes?

2017-05-03 18:21 UTC, aresxs91 commented
I see, great then.

I want to have a closer look at some of the validity checks, not all of them are needed so I'll need some more time on that. Will let you know, thanks!

2017-05-03 18:22 UTC, aresxs91 commented
I see, great then.

I want to have a closer look at some of the validity checks, not all of them are needed so I'll need some more time on that. Will let you know, thanks!

2017-05-03 18:23 UTC, sckott commented
okay

2017-05-04 09:12 UTC, aresxs91 commented
Hi @sckott, after a quick review, there shouldn't be any immediate changes I'll need to do on the filter values validity checks. There may be edge cases not captured but I think for the most part, they should be ready to go. If there's nothing else to add, let's get this into production!

2017-05-04 17:10 UTC, sckott commented
okay, looks good

2017-05-04 17:10 UTC, merged